name: Docker Deploy

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  
  build:
    env:
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Image
        run: docker build -t bpinkerton/quizlite .
      - name: Docker Push
        run: docker push bpinkerton/quizlite
        
